"""Regression dataset convention for the Agent Playground.

Implements design.md §9.3: every experiment has a single ``EvaluationDataset``
named ``regression_suite_<experiment_id>`` that grows monotonically with the
test cases generated by :class:`mlflow.playground.test_case_generator.TestCaseGenerator`.

The dataset is created lazily on first write so empty experiments don't get a
stub dataset they never use. Each row carries ``issue_id`` / ``source_trace_id``
tags for lineage and a ``promoted`` tag flipped to ``"true"`` when the issue is
accepted (per §9.3 — only accepted issues' tests run as gates).
"""

from __future__ import annotations

from mlflow.exceptions import MlflowException
from mlflow.genai.datasets import create_dataset, get_dataset
from mlflow.genai.datasets.evaluation_dataset import EvaluationDataset
from mlflow.playground.test_case_generator import GeneratedTestCase, TestCaseGenerator
from mlflow.protos.databricks_pb2 import RESOURCE_DOES_NOT_EXIST, ErrorCode

REGRESSION_DATASET_PREFIX = "regression_suite_"


def regression_dataset_name(experiment_id: str) -> str:
    return f"{REGRESSION_DATASET_PREFIX}{experiment_id}"


def get_or_create_regression_dataset(experiment_id: str) -> EvaluationDataset:
    name = regression_dataset_name(experiment_id)
    try:
        return get_dataset(name=name)
    except MlflowException as e:
        if e.error_code != ErrorCode.Name(RESOURCE_DOES_NOT_EXIST):
            raise
        return create_dataset(name=name, experiment_id=experiment_id)


def append_test_case(
    experiment_id: str,
    test_case: GeneratedTestCase,
    *,
    issue_id: str | None = None,
    source_trace_id: str | None = None,
    promoted: bool = False,
) -> EvaluationDataset:
    record = TestCaseGenerator.to_dataset_record(
        test_case, issue_id=issue_id, source_trace_id=source_trace_id
    )
    record["tags"]["promoted"] = "true" if promoted else "false"
    # The store's `upsert_dataset_records` dedupes by `sha256(json.dumps(inputs))`,
    # which means two test cases anchored to the same conversation prefix would
    # otherwise collide and the older one would be overwritten. Sticking
    # `_test_case_id` into `inputs` makes every case's hash unique. Readers
    # (the agent invocation, the regression runner's group key, the
    # `list_regression_cases` shape transform) all key off `inputs.messages`
    # and ignore extra keys, so this is invisible to them.
    record["inputs"] = {**record["inputs"], "_test_case_id": test_case.test_case_id}
    dataset = get_or_create_regression_dataset(experiment_id)
    dataset.merge_records([record])
    return dataset


def update_test_case(
    experiment_id: str,
    test_case_id: str,
    *,
    question: str | None = None,
    assertion: dict[str, list[str]] | None = None,
    judge: dict[str, str | None] | None = None,
) -> None:
    """Edit one test case in place. ``None`` for any field means "keep what
    was there." Performs a delete-then-insert because ``upsert_dataset_records``
    dedupes by hash of ``inputs``: changing the question would otherwise
    insert a second row with the same ``test_case_id`` instead of replacing
    the original.

    No-op when the ``test_case_id`` doesn't resolve. Preserves all existing
    tags (``issue_id``, ``source_trace_id``, ``promoted``) and the original
    ``test_case_id`` itself, so external lineage links don't break.
    """
    import json

    try:
        dataset = get_dataset(name=regression_dataset_name(experiment_id))
    except MlflowException as e:
        if e.error_code == ErrorCode.Name(RESOURCE_DOES_NOT_EXIST):
            return
        raise

    df = dataset.to_df()
    if df.empty:
        return

    def _coerce(v):
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (ValueError, TypeError):
                return v
        return v

    target_row = None
    target_record_id = None
    for row in df.to_dict(orient="records"):
        expectations = _coerce(row.get("expectations") or {})
        if isinstance(expectations, dict) and expectations.get("test_case_id") == test_case_id:
            target_row = row
            target_record_id = row.get("dataset_record_id")
            break
    if target_row is None:
        return

    existing_inputs = _coerce(target_row.get("inputs") or {})
    existing_messages = (
        _coerce(existing_inputs.get("messages") or [])
        if isinstance(existing_inputs, dict)
        else []
    )
    if not isinstance(existing_messages, list):
        existing_messages = []
    existing_expectations = _coerce(target_row.get("expectations") or {})
    if not isinstance(existing_expectations, dict):
        existing_expectations = {}
    existing_spec = existing_expectations.get("test_spec") or {}
    if not isinstance(existing_spec, dict):
        existing_spec = {}
    existing_tags = _coerce(target_row.get("tags") or {})
    if not isinstance(existing_tags, dict):
        existing_tags = {}

    # Build the new messages list. If the caller supplied a fresh question we
    # rewrite the LAST user turn — anything before it is preserved (the agent
    # may need that prefix for context). If there's no user turn at all we
    # synthesize one.
    new_messages = list(existing_messages)
    if question is not None:
        replaced = False
        for i in range(len(new_messages) - 1, -1, -1):
            msg = new_messages[i]
            if isinstance(msg, dict) and msg.get("role") == "user":
                new_messages[i] = {"role": "user", "content": question}
                replaced = True
                break
        if not replaced:
            new_messages.append({"role": "user", "content": question})

    new_spec = dict(existing_spec)
    if assertion is not None:
        new_spec["strategy"] = "assertion"
        new_spec["assertion"] = {
            "must_contain": list(assertion.get("must_contain") or []),
            "must_not_contain": list(assertion.get("must_not_contain") or []),
            "must_call_tool": list(assertion.get("must_call_tool") or []),
            "must_not_call_tool": list(assertion.get("must_not_call_tool") or []),
        }
        new_spec.pop("judge", None)
    if judge is not None:
        new_spec["strategy"] = "judge"
        new_spec["judge"] = {
            "criteria": judge.get("criteria") or "",
            "expected_response": judge.get("expected_response"),
        }
        new_spec.pop("assertion", None)

    new_record = {
        # `_test_case_id` mirrors the disambiguator `append_test_case` adds —
        # without it the new record's input hash would collide with whatever
        # else lives at the same conversation prefix.
        "inputs": {"messages": new_messages, "_test_case_id": test_case_id},
        "expectations": {
            **{k: v for k, v in existing_expectations.items() if k != "test_spec"},
            "test_case_id": test_case_id,
            "test_spec": new_spec,
        },
        "tags": dict(existing_tags),
    }

    # Delete-then-insert. Insert first would risk a transient duplicate; the
    # cockpit's list_regression_cases tolerates orphans, but a duplicate
    # share-the-same-test_case_id row is worse than a brief no-row state.
    if target_record_id:
        dataset.delete_records([target_record_id])
    dataset.merge_records([new_record])


def delete_test_case(experiment_id: str, test_case_id: str) -> None:
    """Remove one test case by ``test_case_id``. No-op if it doesn't exist —
    matches HTTP DELETE semantics so a double-click in the UI doesn't error.

    Resolves ``test_case_id`` (stored in ``expectations``) to one or more
    ``dataset_record_id`` values, then calls ``delete_records`` which works
    in record-id space. Multiple matches are rare but possible if a case
    was re-dispatched and we want to keep the API forgiving — delete all
    rows that claim the same ``test_case_id``.
    """
    import json

    try:
        dataset = get_dataset(name=regression_dataset_name(experiment_id))
    except MlflowException as e:
        if e.error_code == ErrorCode.Name(RESOURCE_DOES_NOT_EXIST):
            return
        raise

    df = dataset.to_df()
    if df.empty:
        return

    def _coerce(v):
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (ValueError, TypeError):
                return v
        return v

    record_ids: list[str] = []
    for row in df.to_dict(orient="records"):
        expectations = _coerce(row.get("expectations") or {})
        if not isinstance(expectations, dict):
            continue
        if expectations.get("test_case_id") == test_case_id:
            rid = row.get("dataset_record_id")
            if rid:
                record_ids.append(rid)
    if record_ids:
        dataset.delete_records(record_ids)


__all__ = [
    "REGRESSION_DATASET_PREFIX",
    "append_test_case",
    "delete_test_case",
    "get_or_create_regression_dataset",
    "regression_dataset_name",
    "update_test_case",
]
