"""Regression dataset convention for the Agent Playground.

Implements design.md §9.3: every experiment has a single ``EvaluationDataset``
named ``regression_suite_<experiment_id>`` that grows monotonically with the
test cases generated by :class:`mlflow.playground.test_case_generator.TestCaseGenerator`.

The dataset is created lazily on first write so empty experiments don't get a
stub dataset they never use. Each row carries ``issue_id`` / ``source_trace_id``
tags for lineage and a ``promoted`` tag flipped to ``"true"`` when the issue is
accepted (per §9.3 — only accepted issues' tests run as gates).
"""

from __future__ import annotations

from mlflow.exceptions import MlflowException
from mlflow.genai.datasets import create_dataset, get_dataset
from mlflow.genai.datasets.evaluation_dataset import EvaluationDataset
from mlflow.playground.test_case_generator import GeneratedTestCase, TestCaseGenerator
from mlflow.protos.databricks_pb2 import RESOURCE_DOES_NOT_EXIST, ErrorCode

REGRESSION_DATASET_PREFIX = "regression_suite_"


def regression_dataset_name(experiment_id: str) -> str:
    return f"{REGRESSION_DATASET_PREFIX}{experiment_id}"


def get_or_create_regression_dataset(experiment_id: str) -> EvaluationDataset:
    name = regression_dataset_name(experiment_id)
    try:
        return get_dataset(name=name)
    except MlflowException as e:
        if e.error_code != ErrorCode.Name(RESOURCE_DOES_NOT_EXIST):
            raise
        return create_dataset(name=name, experiment_id=experiment_id)


def append_test_case(
    experiment_id: str,
    test_case: GeneratedTestCase,
    *,
    issue_id: str | None = None,
    source_trace_id: str | None = None,
    promoted: bool = False,
) -> EvaluationDataset:
    record = TestCaseGenerator.to_dataset_record(
        test_case, issue_id=issue_id, source_trace_id=source_trace_id
    )
    record["tags"]["promoted"] = "true" if promoted else "false"
    dataset = get_or_create_regression_dataset(experiment_id)
    dataset.merge_records([record])
    return dataset


def delete_test_case(experiment_id: str, test_case_id: str) -> None:
    """Remove one test case by ``test_case_id``. No-op if it doesn't exist —
    matches HTTP DELETE semantics so a double-click in the UI doesn't error.

    Resolves ``test_case_id`` (stored in ``expectations``) to one or more
    ``dataset_record_id`` values, then calls ``delete_records`` which works
    in record-id space. Multiple matches are rare but possible if a case
    was re-dispatched and we want to keep the API forgiving — delete all
    rows that claim the same ``test_case_id``.
    """
    import json

    try:
        dataset = get_dataset(name=regression_dataset_name(experiment_id))
    except MlflowException as e:
        if e.error_code == ErrorCode.Name(RESOURCE_DOES_NOT_EXIST):
            return
        raise

    df = dataset.to_df()
    if df.empty:
        return

    def _coerce(v):
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (ValueError, TypeError):
                return v
        return v

    record_ids: list[str] = []
    for row in df.to_dict(orient="records"):
        expectations = _coerce(row.get("expectations") or {})
        if not isinstance(expectations, dict):
            continue
        if expectations.get("test_case_id") == test_case_id:
            rid = row.get("dataset_record_id")
            if rid:
                record_ids.append(rid)
    if record_ids:
        dataset.delete_records(record_ids)


__all__ = [
    "REGRESSION_DATASET_PREFIX",
    "append_test_case",
    "delete_test_case",
    "get_or_create_regression_dataset",
    "regression_dataset_name",
]
